### ISSUE TITLE
IndexError raised when PreMODIT is applied to H2O lines

### ISSUE THREAD

**Issue by chonma0ctopus** [HajimeKawahara/exojax#275]
With the default setting of x32 (`config.update("jax_enable_x64", False)`), an IndexError occurs when applying PreMODIT to Exomol H2O data as follows.
The error can be superficially circumvented by setting x64 or increasing the number of `crit`.

```
#!/usr/bin/env python
# coding: utf-8

from jax.config import config
from exojax.spec.rtransfer import pressure_layer
from exojax.spec.setrt import gen_wavenumber_grid
from exojax.spec import moldb
from exojax.spec import initspec

#↓↓↓↓↓
config.update("jax_enable_x64", False)  #if True, no error.
crit=1.e-25  #If you increase the crit (such as 1.e-24), no error.
#↑↑↑↑↑

Tgue = 3000.
wls, wll = 15020, 15050
Nx = 2000
nus, wav, reso = gen_wavenumber_grid(wls, wll, Nx, unit="AA", xsmode="premodit")

mdbH2O_orig = moldb.MdbExomol('.database/H2O/1H2-16O/POKAZATEL', nus, crit=crit, Ttyp=Tgue)
print('N=', len(mdbH2O_orig.nu_lines))

interval_contrast = 0.1
dit_grid_resolution = 0.1

lbd_H2O, multi_index_uniqgrid_H2O, elower_grid_H2O, \
ngamma_ref_grid_H2O, n_Texp_grid_H2O, R_H2O, pmarray_H2O = initspec.init_premodit(
    mdbH2O_orig.nu_lines,
    nus,
    mdbH2O_orig.elower,
    mdbH2O_orig.alpha_ref,
    mdbH2O_orig.n_Texp,
    mdbH2O_orig.Sij0,
    Ttyp=Tgue,
    interval_contrast=interval_contrast,
    dit_grid_resolution=dit_grid_resolution,
    warning=False)
```
↓
```
xsmode assumes ESLOG: mode= premodit
Background atmosphere:  H2
Reading transition file
.broad is used.
Broadening code level= a1
N= 5126
/home/tako/miniconda3/lib/python3.9/site-packages/exojax-1.1.3-py3.9.egg/exojax/spec/lsd.py:82: RuntimeWarning: overflow encountered in exp
  x=np.exp(-hcperk*x*(1.0/Ttyp-1.0/Tref))
/home/tako/miniconda3/lib/python3.9/site-packages/exojax-1.1.3-py3.9.egg/exojax/spec/lsd.py:83: RuntimeWarning: overflow encountered in exp
  xv=np.exp(-hcperk*xv*(1.0/Ttyp-1.0/Tref))
uniqidx: 100%|████████████████████████████████| 27/27 [00:00<00:00, 15997.49it/s]
Traceback (most recent call last):
  File "/home/tako/work/debug_premodit_220818.py", line 27, in <module>
    ngamma_ref_grid_H2O, n_Texp_grid_H2O, R_H2O, pmarray_H2O = initspec.init_premodit(
  File "/home/tako/miniconda3/lib/python3.9/site-packages/exojax-1.1.3-py3.9.egg/exojax/spec/initspec.py", line 140, in init_premodit
    lbd, multi_index_uniqgrid = generate_lbd(line_strength_ref, nu_lines, nu_grid, ngamma_ref, ngamma_ref_grid,
  File "/home/tako/miniconda3/lib/python3.9/site-packages/exojax-1.1.3-py3.9.egg/exojax/spec/premodit.py", line 237, in generate_lbd
    lbd = npadd3D_multi_index(lbd, line_strength_ref, cont_nu, index_nu,
  File "/home/tako/miniconda3/lib/python3.9/site-packages/exojax-1.1.3-py3.9.egg/exojax/spec/lsd.py", line 183, in npadd3D_multi_index
    a = npadd3D_direct1D(a, w, cx, ix, direct_cy, direct_iy, cz, iz)
  File "/home/tako/miniconda3/lib/python3.9/site-packages/exojax-1.1.3-py3.9.egg/exojax/spec/lsd.py", line 160, in npadd3D_direct1D
    np.add.at(a, (ix, direct_iy, iz+1), w*(1-cx)*direct_cy*cz)
IndexError: index 45 is out of bounds for axis 2 with size 45
```

**Comment by chonma0ctopus** [comment]
By the way, you may want to modify [Returns](https://github.com/HajimeKawahara/exojax/blob/122b3b8a20836818ce88cae0d894d4f35d66b39f/src/exojax/spec/initspec.py#L113) in the docstrings of the function `init_premodit` in initspec.py. (Sorry I should have noticed that during the PR #265.)
