### ISSUE TITLE
vaex conversion of YT34to10 CH4 line list is killed

### ISSUE THREAD

**Issue by chonma0ctopus** [HajimeKawahara/exojax#310]
When using the CH4 lines in the H-band from **YT34to10**, the `api.MdbExomol` is killed when converting the `.trans.bz2` file to the .hdf5 format.
It works fine with **YT10to10**, so it might be related to the too-large data size?
A sample is below:

```
from exojax.utils.grids import wavenumber_grid
from exojax.spec import api
nus, wav, res = wavenumber_grid(14800, 14900, 1000, unit="AA", xsmode="premodit")
mdbCH4 = api.MdbExomol('.database/CH4/12C-1H4/YT34to10', nus)
print(len(mdbCH4.nu_lines))
```

**Comment by chonma0ctopus** [comment]
Below is the stdout. It looks just killed...
```
xsmode assumes ESLOG in wavenumber space: mode=premodit
/home/tako/ghR/exojax/src/exojax/utils/grids.py:123: UserWarning: Resolution may be too small. R=148350.93939225338
  warnings.warn('Resolution may be too small. R=' + str(resolution),
Background atmosphere:  H2
Reading .database/CH4/12C-1H4/YT34to10/12C-1H4__YT34to10__06700-06800.trans.bz2
Note: Caching line transition data to the vaex format. After the second time, it will become much faster.
Killed
```

When I specify output in the SBATCH on the CfCA server (sorry for a bit inside talk), I get the following output with a BufferError:
```
Traceback (most recent call last):
  File "/home/ishikawahr/anaconda3/envs/cpR7/lib/python3.9/site-packages/vaex/convert.py", line 95, in _from_csv_convert_and_read
    df.close()
  File "/home/ishikawahr/anaconda3/envs/cpR7/lib/python3.9/site-packages/vaex/dataframe.py", line 2198, in close
    self.dataset.close()
  File "/home/ishikawahr/anaconda3/envs/cpR7/lib/python3.9/site-packages/vaex/hdf5/dataset.py", line 416, in close
    super().close()
  File "/home/ishikawahr/anaconda3/envs/cpR7/lib/python3.9/site-packages/vaex/dataset_mmap.py", line 90, in close
    memmap.close()
BufferError: cannot close exported pointers exist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/gwork0/ishikawahr/ghR/exojax/src/exojax/spec/exomolapi.py", line 136, in read_trans
    dat = vaex.from_csv(transf, compression='bz2', sep='\s+',
  File "/home/ishikawahr/anaconda3/envs/cpR7/lib/python3.9/site-packages/vaex/__init__.py", line 567, in from_csv
    vaex.convert.convert_csv(
  File "/home/ishikawahr/anaconda3/envs/cpR7/lib/python3.9/site-packages/vaex/convert.py", line 52, in convert_csv
    cached_output(*args, **kwargs)
  File "/home/ishikawahr/anaconda3/envs/cpR7/lib/python3.9/site-packages/vaex/cache.py", line 422, in call
    value = callable(*args, **kwargs)
  File "/home/ishikawahr/anaconda3/envs/cpR7/lib/python3.9/site-packages/vaex/convert.py", line 51, in cached_output
    _from_csv_convert_and_read(path_input, path_output=path_output, fs_options=fs_options_input, fs=fs_input, progress=progress, **kwargs)
  File "/home/ishikawahr/anaconda3/envs/cpR7/lib/python3.9/site-packages/vaex/convert.py", line 98, in _from_csv_convert_and_read
    log.error('Could not close or delete intermediate file %s used to convert %s to single file: %s', (df_path, csv_path, path_output))
  File "/home/ishikawahr/anaconda3/envs/cpR7/lib/python3.9/logging/__init__.py", line 1475, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/home/ishikawahr/anaconda3/envs/cpR7/lib/python3.9/logging/__init__.py", line 1589, in _log
    self.handle(record)
  File "/home/ishikawahr/anaconda3/envs/cpR7/lib/python3.9/logging/__init__.py", line 1599, in handle
    self.callHandlers(record)
  File "/home/ishikawahr/anaconda3/envs/cpR7/lib/python3.9/logging/__init__.py", line 1661, in callHandlers
    hdlr.handle(record)
  File "/home/ishikawahr/anaconda3/envs/cpR7/lib/python3.9/logging/__init__.py", line 952, in handle
    self.emit(record)
  File "/home/ishikawahr/anaconda3/envs/cpR7/lib/python3.9/site-packages/rich/logging.py", line 126, in emit
    message = self.format(record)
  File "/home/ishikawahr/anaconda3/envs/cpR7/lib/python3.9/logging/__init__.py", line 927, in format
    return fmt.format(record)
  File "/home/ishikawahr/anaconda3/envs/cpR7/lib/python3.9/logging/__init__.py", line 663, in format
    record.message = record.getMessage()
  File "/home/ishikawahr/anaconda3/envs/cpR7/lib/python3.9/logging/__init__.py", line 367, in getMessage
    msg = msg % self.args
TypeError: not enough arguments for format string

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ishikawahr/anaconda3/envs/cpR7/lib/python3.9/site-packages/vaex/convert.py", line 95, in _from_csv_convert_and_read
    df.close()
  File "/home/ishikawahr/anaconda3/envs/cpR7/lib/python3.9/site-packages/vaex/dataframe.py", line 2198, in close
    self.dataset.close()
  File "/home/ishikawahr/anaconda3/envs/cpR7/lib/python3.9/site-packages/vaex/hdf5/dataset.py", line 416, in close
    super().close()
  File "/home/ishikawahr/anaconda3/envs/cpR7/lib/python3.9/site-packages/vaex/dataset_mmap.py", line 90, in close
    memmap.close()
BufferError: cannot close exported pointers exist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cfca-work/ishikawahr/work/bugreport_YT34to10_221104.py", line 4, in <module>
    mdbCH4 = moldb.MdbExomol('.database/CH4/12C-1H4/YT34to10', nus)
  File "/gwork0/ishikawahr/ghR/exojax/src/exojax/spec/moldb.py", line 206, in __init__
    trans = exomolapi.read_trans(trans_file)
  File "/gwork0/ishikawahr/ghR/exojax/src/exojax/spec/exomolapi.py", line 139, in read_trans
    dat = vaex.read_csv(
  File "/home/ishikawahr/anaconda3/envs/cpR7/lib/python3.9/site-packages/vaex/__init__.py", line 594, in read_csv
    return from_csv(filepath_or_buffer, **kwargs)
  File "/home/ishikawahr/anaconda3/envs/cpR7/lib/python3.9/site-packages/vaex/__init__.py", line 567, in from_csv
    vaex.convert.convert_csv(
  File "/home/ishikawahr/anaconda3/envs/cpR7/lib/python3.9/site-packages/vaex/convert.py", line 52, in convert_csv
    cached_output(*args, **kwargs)
  File "/home/ishikawahr/anaconda3/envs/cpR7/lib/python3.9/site-packages/vaex/cache.py", line 429, in call
    value = callable(*args, **kwargs)
  File "/home/ishikawahr/anaconda3/envs/cpR7/lib/python3.9/site-packages/vaex/convert.py", line 51, in cached_output
    _from_csv_convert_and_read(path_input, path_output=path_output, fs_options=fs_options_input, fs=fs_input, progress=progress, **kwargs)
  File "/home/ishikawahr/anaconda3/envs/cpR7/lib/python3.9/site-packages/vaex/convert.py", line 98, in _from_csv_convert_and_read
    log.error('Could not close or delete intermediate file %s used to convert %s to single file: %s', (df_path, csv_path, path_output))
  File "/home/ishikawahr/anaconda3/envs/cpR7/lib/python3.9/logging/__init__.py", line 1475, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/home/ishikawahr/anaconda3/envs/cpR7/lib/python3.9/logging/__init__.py", line 1589, in _log
    self.handle(record)
  File "/home/ishikawahr/anaconda3/envs/cpR7/lib/python3.9/logging/__init__.py", line 1599, in handle
    self.callHandlers(record)
  File "/home/ishikawahr/anaconda3/envs/cpR7/lib/python3.9/logging/__init__.py", line 1661, in callHandlers
    hdlr.handle(record)
  File "/home/ishikawahr/anaconda3/envs/cpR7/lib/python3.9/logging/__init__.py", line 952, in handle
    self.emit(record)
  File "/home/ishikawahr/anaconda3/envs/cpR7/lib/python3.9/site-packages/rich/logging.py", line 126, in emit
    message = self.format(record)
  File "/home/ishikawahr/anaconda3/envs/cpR7/lib/python3.9/logging/__init__.py", line 927, in format
    return fmt.format(record)
  File "/home/ishikawahr/anaconda3/envs/cpR7/lib/python3.9/logging/__init__.py", line 663, in format
    record.message = record.getMessage()
  File "/home/ishikawahr/anaconda3/envs/cpR7/lib/python3.9/logging/__init__.py", line 367, in getMessage
    msg = msg % self.args
TypeError: not enough arguments for format string
```

**Comment by chonma0ctopus** [comment]
I found that even though this killing occurred, the output of the vaex conversion (`.database/CH4/12C-1H4/YT34to10/12C-1H4__YT34to10__06700-06800.trans_BU.hdf5`) was successfully(?) generated somehow.
Moreover, when I ran the same code again after that, it read the `.hdf5` file and ran it to the end without any problem. (For now, for some reason, this is sufficient as a temporary workaround...)

**Comment by HajimeKawahara** [comment]
This was due to DRAM overflow. So, #316 must solve the issue.
