### ISSUE TITLE
bugs found by @ykawashima for v1.4.1

### ISSUE THREAD

**Issue by HajimeKawahara** [HajimeKawahara/exojax#405]
See #404, but I made a new issue for the record (with adding numbering).
----

- [x] 1. I would like to confirm whether the change of the file path in the retrieval tutorial (0af60abd305a04aed50889d158c9f9e77c337c70) is correct or not. I think it is more straightforward to mention the tutorial notebook itself. Or did you intend to mention [this python file](https://github.com/HajimeKawahara/exojax/blob/develop/tests/endtoend/reverse/reverse_premodit.py)? (In the latter case, some parts need to be fixed to be compatible with the current version.)
- [x] 2. I got the following error for [tests/integration/premodit/checindex.py](https://github.com/HajimeKawahara/exojax/blob/develop/tests/integration/premodit/checkindex.py) due to the change of the input parameters of init_premodit.
```Traceback (most recent call last):
  File "/home/kawashima/exojax/tests/integration/premodit/checkindex.py", line 28, in <module>
    ngamma_ref_grid_H2O, n_Texp_grid_H2O, R_H2O, pmarray_H2O = initspec.init_premodit(
TypeError: init_premodit() got an unexpected keyword argument 'interval_contrast'
```
- [x] 3. I got the following error for [tests/integration/premodit/line_strength_comparison_exomol.py](https://github.com/HajimeKawahara/exojax/blob/master/tests/integration/premodit/line_strength_comparison_exomol.py) due to the change of the input parameters of unbiased_ngamma_grid. Could you add Tref_broadening parameter? The same thing applies to [tests/integration/premodit/line_strength_comparison_hitemp.py](https://github.com/HajimeKawahara/exojax/blob/master/tests/integration/premodit/line_strength_comparison_hitemp.py). Thank you. 
```
Traceback (most recent call last):
  File "/home/kawashima/exojax/tests/integration/premodit/line_strength_comparison_exomol.py", line 78, in <module>
    ngamma_grid = unbiased_ngamma_grid(Ttest, P, ngamma_ref_grid, n_Texp_grid,
TypeError: unbiased_ngamma_grid() missing 1 required positional argument: 'Tref_broadening'
```
- [x] 4. I got the following errors for [tests/integration/moldb/comparison_api.py](https://github.com/HajimeKawahara/exojax/blob/master/tests/integration/moldb/comparison_api.py) and [tests/integration/moldb/comparison_api_xs.py](https://github.com/HajimeKawahara/exojax/blob/master/tests/integration/moldb/comparison_api_xs.py). I think these two tests are no more needed given that MdbExomol and MdbHit have been discarded in exojax.spec.moldb.
```
Traceback (most recent call last):
  File "/home/kawashima/exojax/tests/integration/moldb/comparison_api.py", line 8, in <module>
    from exojax.spec.moldb import MdbExomol as MdbExomol_orig
ImportError: cannot import name 'MdbExomol' from 'exojax.spec.moldb' (/home/kawashima/anaconda3/lib/python3.9/site-packages/ExoJAX-1.4-py3.9.egg/exojax/spec/moldb.py)
```
```
Traceback (most recent call last):
  File "/home/kawashima/exojax/tests/integration/moldb/comparison_api_xs.py", line 28, in <module>
    mdbCO_moldb = moldb.MdbHit('~/exojax/data/CO/05_hit12.par', nus)
AttributeError: module 'exojax.spec.moldb' has no attribute 'MdbHit'
```
- [x] 5. I got the following error for [tests/integration/moldb/quantum_states_filter_exomol.py](https://github.com/HajimeKawahara/exojax/blob/master/tests/integration/moldb/quantum_states_filter_exomol.py). Maybe v_u and v_l should be replaced by j_upper and j_lower?
```
Traceback (most recent call last):
  File "/home/kawashima/exojax/tests/integration/moldb/quantum_states_filter_exomol.py", line 31, in <module>
    mask = mdb.df["v_u"] - mdb.df["v_l"] == dv
  File "/home/kawashima/anaconda3/lib/python3.9/site-packages/vaex/dataframe.py", line 5395, in __getitem__
    self.validate_expression(item)
  File "/home/kawashima/anaconda3/lib/python3.9/site-packages/vaex/dataframe.py", line 3446, in validate_expression
    raise NameError(str(e)) from None
NameError: Column or variable 'v_u' does not exist. Did you mean: 'v_l'
```
- [x] 6. I got the following errors, saying that the lengeth of mdb.Sij0 is just 1,  for [tests/integration/moldb/quantum_states_filter_hitemp.py](https://github.com/HajimeKawahara/exojax/blob/master/tests/integration/moldb/quantum_states_filter_hitemp.py) and [tests/integration/moldb/quantum_states_filter_hitran_co.py](https://github.com/HajimeKawahara/exojax/blob/master/tests/integration/moldb/quantum_states_filter_hitran_co.py).
I cannot recognize the line where the line strength is assigned when the activate function is used. Or do I misunderstand?
```
Traceback (most recent call last):
  File "/home/kawashima/exojax/tests/integration/moldb/quantum_states_filter_hitemp.py", line 32, in <module>
    plt.plot(1.e4 / mdb.nu_lines,
  File "/home/kawashima/anaconda3/lib/python3.9/site-packages/matplotlib/pyplot.py", line 2740, in plot
    return gca().plot(
  File "/home/kawashima/anaconda3/lib/python3.9/site-packages/matplotlib/axes/_axes.py", line 1662, in plot
    lines = [*self._get_lines(*args, data=data, **kwargs)]
  File "/home/kawashima/anaconda3/lib/python3.9/site-packages/matplotlib/axes/_base.py", line 311, in __call__
    yield from self._plot_args(
  File "/home/kawashima/anaconda3/lib/python3.9/site-packages/matplotlib/axes/_base.py", line 504, in _plot_args
    raise ValueError(f"x and y must have same first dimension, but "
ValueError: x and y must have same first dimension, but have shapes (1300,) and (1,)
```
```
Traceback (most recent call last):
  File "/home/kawashima/exojax/tests/integration/moldb/quantum_states_filter_hitran_co.py", line 28, in <module>
    plt.plot(1.e4 / mdb.nu_lines,
  File "/home/kawashima/anaconda3/lib/python3.9/site-packages/matplotlib/pyplot.py", line 2740, in plot
    return gca().plot(
  File "/home/kawashima/anaconda3/lib/python3.9/site-packages/matplotlib/axes/_axes.py", line 1662, in plot
    lines = [*self._get_lines(*args, data=data, **kwargs)]
  File "/home/kawashima/anaconda3/lib/python3.9/site-packages/matplotlib/axes/_base.py", line 311, in __call__
    yield from self._plot_args(
  File "/home/kawashima/anaconda3/lib/python3.9/site-packages/matplotlib/axes/_base.py", line 504, in _plot_args
    raise ValueError(f"x and y must have same first dimension, but "
ValueError: x and y must have same first dimension, but have shapes (634,) and (1,)
```

**Comment by HajimeKawahara** [comment]
5. is really bug. It should have ``v_l`` and ``v_u`` and it had, but now is not available...

**Comment by HajimeKawahara** [comment]
6. ``Sij0`` is now deprecated. Use ``line_strength_ref``.

``tests/integration/moldb/quantum_states_filter_hitran_co.py).`` requires ``develop`` branch of ``radis``.

**Comment by HajimeKawahara** [comment]
1. Thanks. The former one is correct. I think all of the bugs have been fixed.
