### ISSUE TITLE
Current radis version is imcompatible with mdbHitemp 

### ISSUE THREAD

**Issue by HajimeKawahara** [HajimeKawahara/exojax#435]
Starting to figure out problems..
Related #397

**Comment by HajimeKawahara** [comment]
Uncomment test_hitemp
```
exoplanet01:~/exojax/tests/integration/api(nonairbug)>python api_hitran_hitemp_test.py 
xsmode =  premodit
xsmode assumes ESLOG in wavenumber space: mode=premodit
======================================================================
We changed the policy of the order of wavenumber/wavelength grids
wavenumber grid should be in ascending order and now 
users can specify the order of the wavelength grid by themselves.
Your wavelength grid is in ***  descending  *** order
This might causes the bug if you update ExoJAX. 
Note that the older ExoJAX assumes ascending order as wavelength grid.
======================================================================
Downloading 05_HITEMP2019.par.bz2 for CO (1/1).
Download complete. Parsing CO database to /home/exoplanet01/exojax/tests/integration/api/CO-05_HITEMP2019.hdf5
Traceback (most recent call last):
  File "/home/exoplanet01/exojax/tests/integration/api/api_hitran_hitemp_test.py", line 60, in <module>
    test_Hitemp()
  File "/home/exoplanet01/exojax/tests/integration/api/api_hitran_hitemp_test.py", line 19, in test_Hitemp
    mdb = api.MdbHitemp("CO",nus)
  File "/home/exoplanet01/exojax/src/exojax/spec/api.py", line 768, in __init__
    df = self.load(
  File "/home/exoplanet01/anaconda3/lib/python3.10/site-packages/radis-0.15-py3.10-linux-x86_64.egg/radis/api/dbmanager.py", line 465, in load
    return mgr.load(
  File "/home/exoplanet01/anaconda3/lib/python3.10/site-packages/radis-0.15-py3.10-linux-x86_64.egg/radis/api/hdf5.py", line 374, in load
    df = df[columns]
  File "/home/exoplanet01/anaconda3/lib/python3.10/site-packages/vaex/dataframe.py", line 5403, in __getitem__
    if isinstance(item[0], slice):
IndexError: list index out of range

```

**Comment by HajimeKawahara** [comment]
The reason of the above error is not `column=None` but `columns = (None,)`, for multiple files, then it fails at [here](https://github.com/radis/radis/blob/0cb1a259d02fe7d9ad956a29c04abb44dd993324/radis/api/hdf5.py#L373)
```python
if columns is not None:
                df = df[columns]
```

**Comment by HajimeKawahara** [comment]
@ykawashima at least in my environment, a small correction of `radis/api.hdf5.py` solved the loading error. I pushed the correction at [hitemp_load](https://github.com/radis/radis/tree/hitemp_load) branch. Can you check it?

The sample code I used for checking:
```python
from exojax.spec import api
from exojax.utils.grids import wavenumber_grid
nus, wav, r = wavenumber_grid(24000.0, 26000.0, 1000, unit="AA", xsmode="premodit")
mdb = api.MdbHitemp("CO", nus, inherit_dataframe=True)

# manual non-air broadening
from exojax.spec.qstate import m_transition_state
from exojax.spec.nonair import gamma_nonair, temperature_exponent_nonair
from exojax.spec.nonair import nonair_coeff_CO_in_H2
df_mask = mdb.df[mdb.df_load_mask] # wavenumber masking
m = m_transition_state(df_mask["jl"],df_mask["branch"])
n_Texp_H2 = temperature_exponent_nonair(m, nonair_coeff_CO_in_H2).values
gamma_ref_H2 = gamma_nonair(m, nonair_coeff_CO_in_H2).values
```

**Comment by HajimeKawahara** [comment]
@ykawashima  Ah, sorry, this is a different error from one  you reported. wait a while.

**Comment by HajimeKawahara** [comment]
submitted to Radis [PR #636](https://github.com/radis/radis/pull/636)

**Comment by HajimeKawahara** [comment]
Radis PR 636 merged
