### ISSUE TITLE
Error in MdbExomol when code level in .broad file is 'a1'

### ISSUE THREAD

**Issue by sh-tada** [HajimeKawahara/exojax#458]
I encountered an error while using `MdbExomol`. This error seems to occur when the code level in the .broad file "a1".
It appears that this issue is related to a bug in the [exomolapi.py](https://github.com/radis/radis/blob/develop/radis/api/exomolapi.py) file in radis. I am planning to submit a Pull Request to radis to address this issue.

- Error messages
```
Traceback (most recent call last):
  File "/home/tada/anaconda3/envs/exojax/lib/python3.10/site-packages/ExoJAX-1.4.3-py3.10.egg/exojax/spec/api.py", line 190, in activate
    self.compute_broadening(self.jlower.astype(int), self.jupper.astype(int))
AttributeError: 'MdbExomol' object has no attribute 'compute_broadening'. Did you mean: 'computebroadening'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tada/exojax/spectrum.py", line 78, in <module>
    mdb_H2O = MdbExomol(".db_ExoMol/H2O/1H2-16O/POKAZATEL/", nu_grid, gpu_transfer=False)
  File "/home/tada/anaconda3/envs/exojax/lib/python3.10/site-packages/ExoJAX-1.4.3-py3.10.egg/exojax/spec/api.py", line 141, in init
    self.activate(df)
  File "/home/tada/anaconda3/envs/exojax/lib/python3.10/site-packages/ExoJAX-1.4.3-py3.10.egg/exojax/spec/api.py", line 192, in activate
    self.set_broadening_coef(df[mask], add_columns=False)
  File "/home/tada/exojax/exojax/src/radis/radis/api/exomolapi.py", line 1285, in set_broadening_coef
    jlower_max=np.max(df["jlower"]),
  File "/home/tada/anaconda3/envs/exojax/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 2810, in max
    return _wrapreduction(a, np.maximum, 'max', axis, None, out,
  File "/home/tada/anaconda3/envs/exojax/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 86, in _wrapreduction
    return reduction(axis=axis, out=out, **passkwargs)
TypeError: Expression.max() got an unexpected keyword argument 'axis' 
```

**Comment by HajimeKawahara** [comment]
merged into develop in radis
